# file docker-compose.yml dùng để cấu hình các dịch vụ trong project
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    container_name: zookeeper-1
    # restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-network

  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka-1 
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INSIDE://kafka-1:9093,OUTSIDE://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=OUTSIDE
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  init-kafka:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    networks:
      - app-network
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9093 --list
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka-1:9093 --create --if-not-exists --topic thpt_2024 --replication-factor 1 --partitions 5

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka-1:9093 --list
      "
 
  # cấu hình dịch vụ crawler
  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    container_name: crawler-1
    depends_on:
      - kafka
    volumes:
      - ./crawler/target/crawler-1.0-SNAPSHOT.jar:/app/crawler.jar
    networks:
      - app-network

  db:
      image: postgres:13
      container_name: postgres-1
      environment:
        POSTGRES_DB: mydatabase
        POSTGRES_USER: myuser
        POSTGRES_HOST_AUTH_METHOD: trust
      ports:
        - "5432:5432"
      networks:
        - app-network

networks:
  app-network:
    driver: bridge